### ISSUE TITLE
errors while running scriplet during `dnf module install nginx-f26`

### ISSUE THREAD

**Issue by miabbott** [modularity-modules/nginx#4]
Saw an `AttributeError` and `Failed to connect to bus` while doing the install;  still seems to have installed correctly, though.

```
# dnf module install nginx-f26
Python detected LC_CTYPE=C: LC_CTYPE & LANG coerced to C.UTF-8 (set another locale or PYTHONCOERCECLOCALE=0 to disable this locale coercion behavior).
Last metadata expiration check: 0:00:54 ago on Wed Jul 26 17:55:46 2017.
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                            Arch                                     Version                                                        Repository                                        Size
===================================================================================================================================================================================================================
Installing:
 nginx                                              x86_64                                   1:1.10.3-1.module_3e63186e                                     fedora-modular                                   509 k
Installing dependencies:
 gc                                                 x86_64                                   7.6.0-5.module_39876f37                                        fedora-modular                                   108 k
 gperftools-libs                                    x86_64                                   2.5.93-1.module_836062be                                       fedora-modular                                   280 k
 guile                                              x86_64                                   5:2.0.14-1.module_39876f37                                     fedora-modular                                   3.5 M
 libatomic_ops                                      x86_64                                   7.4.4-2.module_39876f37                                        fedora-modular                                    31 k
 libstdc++                                          x86_64                                   7.1.1-1.module_39876f37                                        fedora-modular                                   456 k
 libtool-ltdl                                       x86_64                                   2.4.6-18.module_836062be                                       fedora-modular                                    55 k
 libunwind                                          x86_64                                   1.2-1.module_836062be                                          fedora-modular                                    64 k
 make                                               x86_64                                   1:4.2.1-2.module_39876f37                                      fedora-modular                                   493 k
 nginx-filesystem                                   noarch                                   1:1.10.3-1.module_3e63186e                                     fedora-modular                                    20 k
 nginx-mimetypes                                    noarch                                   2.1.48-1.module_41a7111c                                       fedora-modular                                    26 k
 openssl                                            x86_64                                   1:1.1.0e-1.module_39876f37                                     fedora-modular                                   551 k

Transaction Summary
===================================================================================================================================================================================================================
Install  12 Packages

Total download size: 6.0 M
Installed size: 19 M
Is this ok [y/N]: y
Downloading Packages:
(1/12): nginx-filesystem-1.10.3-1.module_3e63186e.noarch.rpm                                                                                                                        19 kB/s |  20 kB     00:01    
(2/12): openssl-1.1.0e-1.module_39876f37.x86_64.rpm                                                                                                                                861 kB/s | 551 kB     00:00    
(3/12): nginx-1.10.3-1.module_3e63186e.x86_64.rpm                                                                                                                                  294 kB/s | 509 kB     00:01    
(4/12): gperftools-libs-2.5.93-1.module_836062be.x86_64.rpm                                                                                                                        154 kB/s | 280 kB     00:01    
(5/12): libstdc++-7.1.1-1.module_39876f37.x86_64.rpm                                                                                                                               1.7 MB/s | 456 kB     00:00    
(6/12): gc-7.6.0-5.module_39876f37.x86_64.rpm                                                                                                                                      501 kB/s | 108 kB     00:00    
(7/12): make-4.2.1-2.module_39876f37.x86_64.rpm                                                                                                                                    1.2 MB/s | 493 kB     00:00    
(8/12): libunwind-1.2-1.module_836062be.x86_64.rpm                                                                                                                                 115 kB/s |  64 kB     00:00    
(9/12): libatomic_ops-7.4.4-2.module_39876f37.x86_64.rpm                                                                                                                           129 kB/s |  31 kB     00:00    
(10/12): nginx-mimetypes-2.1.48-1.module_41a7111c.noarch.rpm                                                                                                                       117 kB/s |  26 kB     00:00    
(11/12): libtool-ltdl-2.4.6-18.module_836062be.x86_64.rpm                                                                                                                           77 kB/s |  55 kB     00:00    
(12/12): guile-2.0.14-1.module_39876f37.x86_64.rpm                                                                                                                                 1.7 MB/s | 3.5 MB     00:02    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                              1.4 MB/s | 6.0 MB     00:04     
warning: /var/cache/dnf/fedora-modular-ee159af26e0fc2e5/packages/nginx-1.10.3-1.module_3e63186e.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID a3cc4e62: NOKEY
Importing GPG key 0xA3CC4E62:
 Userid     : "Modular Fedora (fedora-modularity) <fedora-modularity@fedoraproject.org>"
 Fingerprint: EC2F 3D1D B70C 6E48 A719 3B5F 5BC1 B527 A3CC 4E62
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-modularity
Is this ok [y/N]: y
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                           1/1 
  Installing       : libstdc++-7.1.1-1.module_39876f37.x86_64                                                                                                                                                 1/12 
  Running scriptlet: libstdc++-7.1.1-1.module_39876f37.x86_64                                                                                                                                                 1/12 
  Running scriptlet: nginx-filesystem-1:1.10.3-1.module_3e63186e.noarch                                                                                                                                       2/12 
  Installing       : nginx-filesystem-1:1.10.3-1.module_3e63186e.noarch                                                                                                                                       2/12 
  Installing       : nginx-mimetypes-2.1.48-1.module_41a7111c.noarch                                                                                                                                          3/12 
  Installing       : libtool-ltdl-2.4.6-18.module_836062be.x86_64                                                                                                                                             4/12 
  Running scriptlet: libtool-ltdl-2.4.6-18.module_836062be.x86_64                                                                                                                                             4/12 
  Installing       : libatomic_ops-7.4.4-2.module_39876f37.x86_64                                                                                                                                             5/12 
  Running scriptlet: libatomic_ops-7.4.4-2.module_39876f37.x86_64                                                                                                                                             5/12 
  Installing       : gc-7.6.0-5.module_39876f37.x86_64                                                                                                                                                        6/12 
  Running scriptlet: gc-7.6.0-5.module_39876f37.x86_64                                                                                                                                                        6/12 
  Installing       : guile-5:2.0.14-1.module_39876f37.x86_64                                                                                                                                                  7/12 
  Running scriptlet: guile-5:2.0.14-1.module_39876f37.x86_64                                                                                                                                                  7/12 
  Installing       : make-1:4.2.1-2.module_39876f37.x86_64                                                                                                                                                    8/12 
  Running scriptlet: make-1:4.2.1-2.module_39876f37.x86_64                                                                                                                                                    8/12 
  Installing       : openssl-1:1.1.0e-1.module_39876f37.x86_64                                                                                                                                                9/12 
  Installing       : libunwind-1.2-1.module_836062be.x86_64                                                                                                                                                  10/12 
  Running scriptlet: libunwind-1.2-1.module_836062be.x86_64                                                                                                                                                  10/12 
  Installing       : gperftools-libs-2.5.93-1.module_836062be.x86_64                                                                                                                                         11/12 
  Running scriptlet: gperftools-libs-2.5.93-1.module_836062be.x86_64                                                                                                                                         11/12 
  Installing       : nginx-1:1.10.3-1.module_3e63186e.x86_64                                                                                                                                                 12/12 
  Running scriptlet: nginx-1:1.10.3-1.module_3e63186e.x86_64                                                                                                                                                 12/12 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf/yum/rpmtrans.py", line 433, in callback
    self._instCloseFile(key)
  File "/usr/lib/python3.6/site-packages/dnf/yum/rpmtrans.py", line 514, in _instCloseFile
    display.progress(None, action, None, None, None, None)
  File "/usr/lib/python3.6/site-packages/dnf/modules.py", line 505, in progress
    conf.enabled = True
AttributeError: 'NoneType' object has no attribute 'enabled'

  Running scriptlet: guile-5:2.0.14-1.module_39876f37.x86_64                                                                                                                                                 12/12 
  Running scriptlet: nginx-1:1.10.3-1.module_3e63186e.x86_64                                                                                                                                                 12/12 
Failed to connect to bus: No such file or directory
  Verifying        : nginx-1:1.10.3-1.module_3e63186e.x86_64                                                                                                                                                  1/12 
  Verifying        : gperftools-libs-2.5.93-1.module_836062be.x86_64                                                                                                                                          2/12 
  Verifying        : nginx-filesystem-1:1.10.3-1.module_3e63186e.noarch                                                                                                                                       3/12 
  Verifying        : openssl-1:1.1.0e-1.module_39876f37.x86_64                                                                                                                                                4/12 
  Verifying        : libstdc++-7.1.1-1.module_39876f37.x86_64                                                                                                                                                 5/12 
  Verifying        : libunwind-1.2-1.module_836062be.x86_64                                                                                                                                                   6/12 
  Verifying        : make-1:4.2.1-2.module_39876f37.x86_64                                                                                                                                                    7/12 
  Verifying        : gc-7.6.0-5.module_39876f37.x86_64                                                                                                                                                        8/12 
  Verifying        : guile-5:2.0.14-1.module_39876f37.x86_64                                                                                                                                                  9/12 
  Verifying        : libatomic_ops-7.4.4-2.module_39876f37.x86_64                                                                                                                                            10/12 
  Verifying        : nginx-mimetypes-2.1.48-1.module_41a7111c.noarch                                                                                                                                         11/12 
  Verifying        : libtool-ltdl-2.4.6-18.module_836062be.x86_64                                                                                                                                            12/12 

Installed:
  nginx.x86_64 1:1.10.3-1.module_3e63186e            gc.x86_64 7.6.0-5.module_39876f37                        gperftools-libs.x86_64 2.5.93-1.module_836062be       guile.x86_64 5:2.0.14-1.module_39876f37        
  libatomic_ops.x86_64 7.4.4-2.module_39876f37       libstdc++.x86_64 7.1.1-1.module_39876f37                 libtool-ltdl.x86_64 2.4.6-18.module_836062be          libunwind.x86_64 1.2-1.module_836062be         
  make.x86_64 1:4.2.1-2.module_39876f37              nginx-filesystem.noarch 1:1.10.3-1.module_3e63186e       nginx-mimetypes.noarch 2.1.48-1.module_41a7111c       openssl.x86_64 1:1.1.0e-1.module_39876f37      

Complete!
```

**Comment by nphilipp** [comment]
There have been many fixes with DNF meanwhile and I haven't seen this, closing now, feel free to reopen if you see it again.
